### ISSUE TITLE
HTML - Add Sidebar to eventually contain favorite GIFs

### ISSUE THREAD

**Issue by Henryhankdc** [Henryhankdc/animating-hollywood#17]

**Comment by DrZYin** [comment]
I propose we add a white heart at each picture's bottom right. When user clicks the heart, it toggles to red, and the gif is added to favorite.

User then clicks a button in the nav bar to access a separate page containing all favorite gifs.

I could be assigned to do this when mvp is done.

**Comment by DrZYin** [comment]
decided to go with separate favorite page after group discussion
